version: '3'

services:
  postgres:
    image: postgres:12.17-alpine3.19
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cms
    ports:
      - '5432:5432'
    volumes:
      - data:/data/db

volumes:
  data:
